version: '3.8'
services:


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 66886388babu
      POSTGRES_DB: employee_management_system
    ports:
      - 5432:5432


  src:
    build: .
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 66886388babu
    depends_on:
      - db

